name: imageforge_tester
description: Flutter app to test ImageForge AI API features
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  
  # Networking
  dio: ^5.4.0
  http: ^1.1.2
  
  # Image
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  photo_view: ^0.14.0
  
  # Storage
  path_provider: ^2.1.2
  permission_handler: ^11.2.0
  
  # State Management
  provider: ^6.1.1
  
  # Utils
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/
